### ISSUE TITLE
FabricAPI link not working

### ISSUE THREAD

**Issue by JesseRWeigel** [MineDojo/Voyager#11] opened 2023-05-27 13:07 UTC
When I try to follow the link to the FabricAPI in `fabric_mods_install.md` I get a 404 error. https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/3891323

**Comment by world-DESIGNER** [comment] 2023-05-27 13:16
I don't think that's an issue with this project
the problem is the website

**Comment by Ellen7ions** [comment] 2023-05-27 13:36
fabric api disappeared in the curseforge, i don't the reason. but you can download it from [here](https://modrinth.com/mod/fabric-api)

**Comment by JesseRWeigel** [comment] 2023-05-27 15:18
I created a PR to fix it: #12

**Comment by xieleo5** [comment] 2023-05-28 03:44
I just merged the PR. Thanks for your efforts!

**Closed by xieleo5** 2023-05-28 03:44 UTC
